export default {
  HOLD_DIE: 'game/HOLD_DIE',
  ROLL_DICE: 'game/ROLL_DICE',
  SET_3_OF_A_KIND: 'game/SET_3_OF_A_KIND',
  SET_4_OF_A_KIND: 'game/SET_4_OF_A_KIND',
  SET_CHANCE: 'game/SET_CHANCE',
  SET_DINKZEE: 'game/SET_DINKZEE',
  SET_FULL_HOUSE: 'game/SET_FULL_HOUSE',
  SET_LARGE_STRAIGHT: 'game/SET_LARGE_STRAIGHT',
  SET_SMALL_STRAIGHT: 'game/SET_SMALL_STRAIGHT',
  SET_UPPER_VALUE: 'game/SET_UPPER_VALUE'
}
